SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 400
BACKGROUND_COLOR = (10, 20, 30)
FONT_COLOR = (200, 200, 200)

INITIAL_CRITTERS = 20
INITIAL_FOOD = 150
FOOD_SPAWN_RATE = 1
MAX_FOOD = 250
SAVE_FILE = "simulation_state.json"
GENERATION_COUNTER = 0

FOOD_COLOR = (120, 255, 120)
FOOD_RADIUS = 3
FOOD_ENERGY = 0.2

DNA_LENGTH = 50
REPRODUCTION_ENERGY_COST = 0.6
REPRODUCTION_THRESHOLD = 0.8
MUTATION_RATE = 0.05
MUTATION_AMOUNT = 0.15

DNA_NN_START_INDEX = 6
NN_INPUTS = 3
NN_HIDDEN_NODES = 5
NN_OUTPUTS = 2
NN_WEIGHTS_COUNT = (NN_INPUTS*NN_HIDDEN_NODES)+(NN_HIDDEN_NODES*NN_OUTPUTS)

if DNA_LENGTH<DNA_NN_START_INDEX + NN_WEIGHTS_COUNT:
    raise ValueError(f"DNA LENGTH in CONFIG MUST BE ATLEAST {DNA_NN_START_INDEX + NN_WEIGHTS_COUNT} to fit the NN")
